---
author: "S.W. Yu"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xgboost)
library(magrittr)
library(tidyverse)
library(lubridate)
library(data.table)
library(DescTools)
library(gridExtra)
library(ggalluvial)
library(ggiraph)
library(maps)
library(plotly)
options(scipen = 999)
```

```{r}
GA_train <- read_csv(".../GA_train_processed.csv")
GA_test <- read_csv(".../GA_test_processed.csv")
GA_train %<>% as.data.frame()
GA_test %<>% as.data.frame()
GA_train %<>% select(., -X1)
GA_test %<>% select(., -X1)
```

# NA inspection
```{r}
nas <- c()
variable_info <- sapply(
  X = 2:34, 
  FUN = function(X) {
  nas <- c(nas, is.na(GA_train[, X]) %>% sum())
  nas %<>% as.numeric()
    }
  ) %>% as.data.frame()
variable_info <- cbind(variable_info, colnames(GA_train)[-c(1, 34)])
str(variable_info)
colnames(variable_info) <- c("num of NA", "var name")

ggplot() + 
  geom_bar(data = variable_info, aes(x = variable_info$`var name`, y = variable_info$`num of NA`), stat = "identity", fill = "#ff8f59") + 
  theme(panel.background = element_rect(fill = "#ecf5ff"), axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.3)) + 
  labs(title = "barplot for na inspection", x = "variables", y = "number of na") + 
  geom_hline(yintercept = 1708337*0.8, color = "red") + 
  geom_hline(yintercept = 1708337*0.5, color = "darkgreen") + 
  lims(y = c(0, 1708337)) + 
  geom_text(aes(x = 29.5, y = 1470000, label = "80%"), color = "red", size = 4.78) + 
  geom_text(aes(x = 29.5, y = 930000, label = "50%"), color = "darkgreen", size = 4.78)
```

# transactionRevenue

```{r transactionRevenue}
train_transactionRevenue <- GA_train %>% group_by(fullVisitorId) %>% summarise(revenue = sum(transactionRevenue))

train_transactionRevenue <- train_transactionRevenue[which(train_transactionRevenue$revenue!=0), ]

ggplot() + 
  geom_density(data = train_transactionRevenue, aes(x = revenue, y = ..density..), fill = "pink", alpha = 0.8, color = "red") + 
  lims(x = c(-1, 1000000000)) + 
  theme_minimal()
  
```

```{r date}
Sys.setlocale("LC_TIME","C")


train_date_transactionRevenue <- select(GA_train, c(date, transactionRevenue))
train_date_transactionRevenue %<>% mutate(month = substr(ymd(train_date_transactionRevenue$date), 1, 7)) 

train_day_transactionRevenue <- train_date_transactionRevenue %>% group_by(ymd(date)) %>%  summarise(day_revenue = sum(transactionRevenue))
train_day_transactionRevenue %<>% as.data.frame()

train_month_transactionRevenue <- train_date_transactionRevenue %>% group_by(month) %>%  summarise(month_revenue = sum(transactionRevenue))
train_month_transactionRevenue %<>% as.data.frame()




test_date_transactionRevenue <- select(GA_test, c(date, transactionRevenue))
test_date_transactionRevenue %<>% mutate(month = substr(ymd(test_date_transactionRevenue$date), 1, 7)) 

test_day_transactionRevenue <- test_date_transactionRevenue %>% group_by(ymd(date)) %>%  summarise(day_revenue = sum(transactionRevenue))
test_day_transactionRevenue %<>% as.data.frame()

test_month_transactionRevenue <- test_date_transactionRevenue %>% group_by(month) %>%  summarise(month_revenue = sum(transactionRevenue))
test_month_transactionRevenue %<>% as.data.frame()
```

```{r }
ggplot() + 
  geom_line(data = train_day_transactionRevenue, aes(x = `ymd(date)`, y = day_revenue/100000), color = "#6F00D2") + 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 10, hjust = 1)) + 
  labs(title = "daily revenue in training data", x = "date", y = "revenue/100000") + 
  scale_x_date(date_labels = "%Y %m", limits = c(ymd(20160801)+1, ymd(20180430)))  
 

ggplot() + 
  geom_bar(data = train_month_transactionRevenue, aes(x = month, y = month_revenue/100000), stat = "identity", fill = "#6F00D2", width = 0.7) + 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 10, hjust = 1)) + 
  labs(title = "monthly revenue in training data", y = "revenue")
  
  




ggplot() + 
  geom_line(data = test_day_transactionRevenue, aes(x = `ymd(date)`, y = day_revenue/100000), color = "#007500") + 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 10, hjust = 1)) + 
  labs(title = "daily revenue in testing data", x = "date", y = "revenue/100000") + 
  scale_x_date(date_labels = "%Y %m", limits = c(ymd(20180501)+1, ymd(20181031)))  
  

ggplot() + 
  geom_bar(data = test_month_transactionRevenue, aes(x = month, y = month_revenue/100000), stat = "identity", fill = "#007500", width = 0.3) + 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 10, hjust = 1)) + 
  labs(title = "monthly revenue in testing data", y = "revenue")
```

```{r pre hour week}
GA_train_hour <- read_csv(".../GA_train_with_numeric_value(final_remain_NA).csv", col_types = cols(fullVisitorId = col_character()))
GA_train_hour %<>% select(., -X1)
GA_train_hour %<>% as.data.frame()
```

```{r}
visitStartTime_train <- as.POSIXct(GA_train_hour$visitStartTime, tz = "UTC", origin = '1970-01-01')

week_train <- wday(x = format(visitStartTime_train, "%Y-%m-%d"))
week_train <- ifelse(week_train==1, 7, week_train-1)


hour_train <- substr(visitStartTime_train, 11, 13) %>% as.numeric()
GA_train_hour %<>% mutate(week = week_train, hour = hour_train)
```

```{r}
week_hour_transactionRevenue <- select(GA_train_hour, c("fullVisitorId", "week", "hour", "transactionRevenue"))
str(week_hour_transactionRevenue)


week_hour_transactionRevenue <- week_hour_transactionRevenue %>% 
  group_by(fullVisitorId) %>% 
  summarise(
    mode_week = ifelse(is.na(Mode(week)), round(mean(week)), Mode(week))[1], 
    mode_hour = ifelse(is.na(Mode(hour)), round(mean(hour)), Mode(hour))[1], 
    weekhour_revenue = sum(transactionRevenue)
  )

week_hour_transactionRevenue %>% head()
```

```{r}
week_hour_transactionRevenue_no0 <- week_hour_transactionRevenue[which(week_hour_transactionRevenue$weekhour_revenue!=0), ]
```

```{r - week}
week_transactionRevenue_no0 <- week_hour_transactionRevenue_no0 %>% group_by(mode_week) %>% summarise(
  week_times = NROW(mode_week),
  week_revenue = sum(weekhour_revenue),
  week_revenue_mean = mean(weekhour_revenue)
)
```

```{r}
ggplot() + 
  geom_bar(data = week_hour_transactionRevenue_no0, aes(x = mode_week %>% as.factor(), y = ..count.., fill = mode_week %>% as.factor()), width = 0.3) + 
  theme_minimal() + 
  labs(x = "week", y = "count", title = "bar plot for non-zero transaction times from Monday to Sunday") + 
  scale_fill_manual(values = c("pink", "#BE77FF", "#7AFEC6", "#FFBB77", "#80FFFF", "#D6D6AD", "#FFE153"), name = "week", breaks = c(1:7), labels = c("Mon", "Tue", "Wen", "Thr", "Fri", "Sat", "Sun")) + 
  scale_x_discrete(labels = c("Mon", "Tue", "Wen", "Thr", "Fri", "Sat", "Sun"))


ggplot() + 
  geom_bar(data = week_transactionRevenue_no0, aes(x = mode_week %>% as.factor(), y = week_revenue_mean, fill = mode_week %>% as.factor()), stat = "identity", width = 0.3) + 
  theme_minimal() + 
  labs(x = "week", y = "revenue", title = "bar plot for the mean of non-zero transaction revenue from Monday to Sunday") + 
  scale_fill_manual(values = c("pink", "#BE77FF", "#7AFEC6", "#FFBB77", "#80FFFF", "#D6D6AD", "#FFE153"), name = "week", breaks = c(1:7), labels = c("Mon", "Tue", "Wen", "Thr", "Fri", "Sat", "Sun")) + 
  scale_x_discrete(labels = c("Mon", "Tue", "Wen", "Thr", "Fri", "Sat", "Sun"))


week_anova <- lm(weekhour_revenue %>% log1p~factor(mode_week), data = week_hour_transactionRevenue_no0) %>% anova()
week_anova
```

```{r - hour}
hour_transactionRevenue_no0 <- week_hour_transactionRevenue_no0 %>% group_by(mode_hour) %>% summarise(
  hour_times = NROW(mode_hour),
  hour_revenue = sum(weekhour_revenue),
  hour_revenue_mean = mean(weekhour_revenue)
)
```

```{r}
ggplot() + 
  geom_line(data = hour_transactionRevenue_no0, aes(x = mode_hour, y = hour_revenue_mean), color = "#D9006C", size = 1.2) + 
  geom_point(data = hour_transactionRevenue_no0, aes(x = mode_hour, y = hour_revenue_mean), color = "#AE0000", size = 2.2) + 
  theme_minimal() + 
  theme(panel.background = element_rect(fill = "#FFFAF4",color = "white")) + 
  labs(x = "hour", y = "revenue", title = "bar plot for the mean of non-zero transaction revenue \n from to 0 a.m. to 23 p.m.") + 
  scale_x_continuous(breaks = c(0:23), labels = c(0:23))




hour_anova <- lm(weekhour_revenue %>% log1p~factor(mode_hour), data = week_hour_transactionRevenue_no0) %>% anova()
hour_anova
```

```{r login times}
logintimes_transactionRevenue <- select(GA_train, c("fullVisitorId", "transactionRevenue"))
logintimes_transactionRevenue <- logintimes_transactionRevenue %>% group_by(fullVisitorId) %>% summarise(
  login_times = NROW(fullVisitorId),
  login_times_revenue = sum(transactionRevenue)
)
logintimes_transactionRevenue_no0 <- logintimes_transactionRevenue[which(logintimes_transactionRevenue$login_times_revenue!=0), ]
```

```{r}
logintimes_transactionRevenue_no0 %>% group_by(login_times) %>% summarise(revenue = sum(login_times_revenue)) %>% ggplot() + 
  geom_point(aes(x = login_times, y = revenue), color = "#6F00D2", size = 1.3) + 
  theme_minimal() + 
  theme(panel.background = element_rect(fill = "#FFFAF4",color = "white")) + 
  labs(y = "revenue", title = "point plot for non-zero transaction revenue with login times")
```

```{r city unknown each }
city_transactionRevenue <- select(GA_train, c(city, transactionRevenue))

city_transactionRevenue <- city_transactionRevenue %>% group_by(city) %>%  summarise(city_revenue = sum(transactionRevenue))

city_transactionRevenue$city <- ifelse(is.na(city_transactionRevenue$city), "Unknown", city_transactionRevenue$city)

city_transactionRevenue <- arrange(city_transactionRevenue, city_revenue %>% desc())



ggplot() + 
  geom_bar(data = city_transactionRevenue[1:30, ], aes(x = reorder(city, city_revenue), y = city_revenue), stat = "identity", color = "#FF79BC", fill = "pink") + 
  theme_minimal() + 
  labs(title = "bar plot for transaction revenue with city", x = "city", y = "revenue") + 
  theme(axis.text.y = element_text(color = c(rep("black", 29), "red"))) + 
  coord_flip()
```

```{r city unknown others}
city_transactionRevenue_unknown <- city_transactionRevenue
city_transactionRevenue_unknown$city <- ifelse(city_transactionRevenue_unknown$city=="Unknown", "Unknown", "Others city")
city_transactionRevenue_unknown <- city_transactionRevenue_unknown %>% group_by(city) %>% summarise(city_revenue = sum(city_revenue))

ggplot() + 
  geom_bar(data = city_transactionRevenue_unknown, aes(x = city, y = city_revenue), stat = "identity", color = "#FF79BC", fill = "pink", width = 0.2) + 
  geom_text(aes(x = 1, y = 1367221730000-100000000000, label = "59.0250%")) + 
  geom_text(aes(x = 2, y = 949123250000-100000000000, label = "40.9750%")) + 
  theme_minimal() + 
  labs(title = "bar plot for transaction revenue with binary city labels", x = "city", y = "revenue") + 
  theme(axis.text.y = element_text(color = c("black", "red"), size = 13)) + 
  coord_flip()
```

```{r networkdomain}
networkDomain_transactionRevenue <- select(GA_train, c(networkDomain, transactionRevenue))

networkDomain_transactionRevenue <- networkDomain_transactionRevenue %>% group_by(networkDomain) %>% summarise(networkDomain_revneue = sum(transactionRevenue)) %>% arrange(., networkDomain_revneue %>% desc())



ggplot() + 
  geom_bar(data = networkDomain_transactionRevenue[1:20, ], aes(x = reorder(networkDomain, networkDomain_revneue), y = networkDomain_revneue), stat = "identity", fill = "#EAC100", color = "#AE8F00") + 
  theme_minimal() + 
  labs(title = "bar plot for transaction revenue with networkDomain", x = "networkDomain", y = "revenue") + 
  theme(axis.text.y = element_text(colour = c(rep("black", 19), "red"))) + 
  coord_flip()
```

```{r networkdomain unknown others}
networkDomain_transactionRevenue_unknown <- networkDomain_transactionRevenue
networkDomain_transactionRevenue_unknown$networkDomain <- ifelse(is.na(networkDomain_transactionRevenue_unknown$networkDomain), "Unknown", "Others networkDomain")
networkDomain_transactionRevenue_unknown <- networkDomain_transactionRevenue_unknown %>% group_by(networkDomain) %>% summarise(networkDomain_revenue = sum(networkDomain_revneue))


ggplot() + 
  geom_bar(data = networkDomain_transactionRevenue_unknown, aes(x = networkDomain, y = networkDomain_revenue), stat = "identity", fill = "#EAC100", color = "#AE8F00", width = 0.2) + 
  geom_text(aes(x = 2, y = 1364096560000-100000000000, label = "58.8900%")) + 
  geom_text(aes(x = 1, y = 952248420000-100000000000, label = "41.1100%")) + 
  theme_minimal() + 
  labs(title = "bar plot for transaction revenue with binary networkDomain labels", x = "networkDomain", y = "revenue") + 
  theme(axis.text.y = element_text(color = c("black", "red"), size = 13)) + 
  coord_flip()
```

```{r}
timeOnSite_transactionRevenue_o <- select(GA_train, c(fullVisitorId, timeOnSite, transactionRevenue))
#time on site 有將近一半na，na的幾乎都是沒交易的
#1.先做na與非na url 交易量圖

timeOnSite_transactionRevenue_o %<>% mutate(labels = ifelse(is.na(timeOnSite_transactionRevenue_o$timeOnSite), "NA", "OVER 0"))
timeOnSite_transactionRevenue <- timeOnSite_transactionRevenue_o %>% group_by(labels) %>% summarise(revenue = sum(transactionRevenue))
timeOnSite_transactionRevenue


timeOnSite_transactionRevenue_no0 <- timeOnSite_transactionRevenue_o[which(timeOnSite_transactionRevenue_o$transactionRevenue!=0), ]

timeOnSite_transactionRevenue_no0 %>% group_by(timeOnSite) %>% summarise(revenue = sum(transactionRevenue)) %>% ggplot() + 
  geom_point(aes(x = timeOnSite, y = revenue), color = "#000079", size = 1) + 
  theme_minimal() + 
  theme(panel.background = element_rect(fill = "#FFFAF4",color = "white")) + 
  labs(y = "revenue", title = "point plot for non-zero transaction revenue with timeOnSite") + 
  lims(y = c(0, 10000000000))
```

```{r channelGrouping}
channelGrouping_transactionRevenue <- select(GA_train, c(fullVisitorId, channelGrouping, transactionRevenue))

channelGrouping_transactionRevenue_no0 <- channelGrouping_transactionRevenue[which(channelGrouping_transactionRevenue$transactionRevenue!=0), ]

channelGrouping_transactionRevenue_no0 <- channelGrouping_transactionRevenue_no0 %>% group_by(channelGrouping) %>% summarise(channelGrouping_revenue = sum(transactionRevenue))

ggplot() + 
  geom_bar(data = channelGrouping_transactionRevenue_no0, aes(x = channelGrouping, y = channelGrouping_revenue/table(channelGrouping_transactionRevenue$channelGrouping), fill = channelGrouping), stat = "identity", width = 0.3) + 
  theme_minimal() + 
  labs(y = "total revenue on each channel / the number of people who access this channel", title = "bar plot for transaction revenue with channelGrouping labels", subtitle = "the number of revenue can be produced on each channel") + 
  theme(axis.text.y = element_text(size = 13)) + 
  coord_flip()
ggsave("test.png")
```

```{r operationsystem}
operationsystem_transactionRevenue_o <- select(GA_train, c("fullVisitorId", "operatingSystem", "transactionRevenue"))
str(operationsystem_transactionRevenue_o)

#some instreasting
operationsystem_transactionRevenue <- operationsystem_transactionRevenue_o %>% group_by(operatingSystem) %>% summarise(revenue = sum(transactionRevenue))

ggplot() + 
  geom_bar(data = operationsystem_transactionRevenue, aes(x = operatingSystem, y = revenue, fill = operatingSystem), stat = "identity", width = 0.8) + 
  theme_minimal() + 
  labs(title = "bar plot for transaction revenue with operationsystem labels") + 
  theme(axis.text.y = element_text(size = 13, colour = c( "red", "black", "red", "black", "black", "red", "red", "red", rep("black", 12), "red", "black", "black", "black"))) + 
  coord_flip()
```

```{r alluvial plot}
alluvial_transactionRevenue_o <- select(GA_train, c("fullVisitorId", "city", "channelGrouping", "operatingSystem", "transactionRevenue"))
alluvial_transactionRevenue <- alluvial_transactionRevenue_o[which(alluvial_transactionRevenue_o$transactionRevenue!=0), ]

alluvial_transactionRevenue$city %>% table() %>% sort()
alluvial_transactionRevenue$city <- ifelse(alluvial_transactionRevenue$city %in% c("New York", "Mountain View", "San Francisco", "Sunnyvale", "Chicago"), alluvial_transactionRevenue$city, "Others") 

alluvial_transactionRevenue$channelGrouping %>% table() %>% sort()
alluvial_transactionRevenue$channelGrouping <- ifelse(alluvial_transactionRevenue$channelGrouping %in% c("Referral", "Organic Search", "Direct"), alluvial_transactionRevenue$channelGrouping, "Others") #, "Paid Search", "Display"

alluvial_transactionRevenue$operatingSystem %>% table() %>% sort()
alluvial_transactionRevenue$operatingSystem <- ifelse(alluvial_transactionRevenue$operatingSystem %in% c("Macintosh", "Windows", "Chrome", "Linux", "iOS", "Android"), alluvial_transactionRevenue$operatingSystem, "Others") #, "Linux", "iOS"


p_alluvial <- (ggplot(alluvial_transactionRevenue,
       aes(y = transactionRevenue %>% log1p, axis1 = city, axis2 = channelGrouping, axis3 = operatingSystem)) +
  geom_alluvium(aes(fill = city), width = 0.1, knot.pos = 0, reverse = F) +
  guides(fill = F) +
  geom_stratum(width = 1/20, reverse = F, fill = "white", color = "black", lty = 6) +
  geom_text(stat = "stratum", infer.label = T, reverse = F, size = 3, family = "Times New Roman") +
  scale_x_continuous(breaks = 1:3, labels = c("city", "channelGrouping", "operatingSystem"), expand = c(0.05, 0.05)) + 
  scale_fill_brewer(type = "qual", palette = "Set1") + 
  theme_minimal() + 
  labs(title = "transactionRevenue by operatingSystem, channelGrouping and city", x = "", y = "weight of revneue")) %>% plot()
ggsave(filename = "alluvial", device = png, plot = p_alluvial, width = 900, height = 600, limitsize = FALSE)
```

```{r world map, echo=FALSE}
world_data <- map_data('world')
#world_data <- fortify(world_data)
colnames(world_data) <- c(colnames(world_data)[1:4], "country", colnames(world_data)[6])

GA_train_world <- GA_train %>% group_by(country) %>% summarise(
  revenue = sum(transactionRevenue),
  login_times = NROW(fullVisitorId),
  timeonsite = sum(timeOnSite, na.rm = T),
  hits = sum(hits)
)ㄢ

GA_train_world$country <- ifelse(GA_train_world$country == "United Kingdom", "UK", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "United States", "USA", GA_train_world$country)
world_data$country <- ifelse(world_data$country %in% c("Antigua", "Barbuda"), "Antigua & Barbuda", world_data$country)
GA_train_world$country <- ifelse(GA_train_world$country == "Bosnia & Herzegovina", "Bosnia and Herzegovina", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "Congo - Brazzaville", "Republic of Congo", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "Congo - Kinshasa", "Democratic Republic of the Congo", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "Cote d<U+00A1><U+00A6>Ivoire", "Ivory Coast", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "Czechia", "Czech Republic", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "Macedonia (FYROM)", "Macedonia", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "Myanmar (Burma)", "Myanmar", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "Sao Tome & Principe", "Sao Tome and Principe", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "St. Barthelemy", "Saint Barthelemy", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "St. Helena", "Saint Helena", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "British Virgin Islands", "Virgin Islands", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "U.S. Virgin Islands", "Virgin Islands", GA_train_world$country)
world_data$country <- ifelse(world_data$country %in% c("Saint Martin", "Bonaire", "Sint Eustatius", "Saba"), "Caribbean Netherlands", world_data$country)
world_data$country <- ifelse(world_data$country %in% c("Saint Kitts", "Nevis"), "St. Kitts & Nevis", world_data$country)
GA_train_world$country <- ifelse(GA_train_world$country == "St. Lucia", "Saint Lucia", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "St. Lucia", "Saint Lucia", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "St. Martin", "Caribbean Netherlands", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "St. Pierre & Miquelon", "Saint Pierre and Miquelon", GA_train_world$country)
GA_train_world$country <- ifelse(GA_train_world$country == "St. Vincent & Grenadines", "Saint Pierre and Miquelon", GA_train_world$country)
world_data$country <- ifelse(world_data$country %in% c("Grenadines", "Saint Vincent"), "St. Vincent & Grenadines", world_data$country)
world_data$country <- ifelse(world_data$country %in% c("Trinidad", "Tobago"), "Trinidad & Tobago", world_data$country)
GA_train_world$country <- ifelse(GA_train_world$country == "Turks & Caicos Islands", "Turks and Caicos Islands", GA_train_world$country)

#grep(pattern = "Kitts", x = world_data$country[-which(world_data$country %in% GA_train_world$country)] %>% unique())



GA_world <- left_join(world_data, GA_train_world, by = "country")
#GA_world %>% colnames() %>% cat(sep = '", "')
GA_world$country <- gsub(pattern = "&", replacement = "and", x = GA_world$country)
GA_world$country <- gsub(pattern = "St.", replacement = "Saint", x = GA_world$country)
#GA_world$country %>% unique()


GA_world %<>% select(., c("long", "lat", "group", "country", "revenue", "login_times", "timeonsite", "hits"))
GA_world$revenue <- ifelse(is.na(GA_world$revenue), 0, GA_world$revenue)
```                   
             
```{r}
p_world <- ggplot() + 
  geom_polygon_interactive(data = GA_world, color = 'gray', size = 0.1, 
                           aes(x = long, y = lat, fill = revenue %>% log1p, group = group, tooltip = sprintf("%s<br/>%s", country, revenue %>% log1p))) + 
  theme_minimal() + 
  scale_fill_gradient2(limits=c(0.00, 28.42), midpoint = 13.92, low = "#E0E0E0", mid = "#7AFEC6", high = "#006000", name = "revenue(log)") + 
  coord_fixed(xlim = c(-180, 180), ylim = c(-100, 100))

ggiraph(code = print(p_world))
```

```{r}
p_world_2 <- ggplot() + 
  geom_polygon(data = GA_world, color = 'gray', size = 0.1, 
               aes(x = long, y = lat, fill = revenue %>% log1p, group = group, text = paste0("COUNTRY: ", country, ", REVENUE: ", revenue %>% log1p %>% round(., 4)))) + 
  theme_minimal() + 
  scale_fill_gradient2(limits=c(0.00, 28.42), midpoint = 13.92, low = "#E0E0E0", mid = "#7AFEC6", high = "#006000", name = "revenue(log)") + 
  coord_fixed(xlim = c(-180, 180), ylim = c(-100, 100))


ggplotly(p_world_2, tooltip = "text")
```

# var important
```{r v.p. xg}
xg_vp1 <- xgb.importance(model = google_xgboost_DEFAULT[[1]])[, 1:2]
xg_vp2 <- xgb.importance(model = google_xgboost_DEFAULT[[2]])[, 1:2]
xg_vp3 <- xgb.importance(model = google_xgboost_DEFAULT[[3]])[, 1:2]
#xg_vp4 <- xgb.importance(model = google_xgboost_DEFAULT[[4]])[, 1:2]
xg_vp5 <- xgb.importance(model = google_xgboost_DEFAULT[[5]])[, 1:2]
xg_vp6 <- xgb.importance(model = google_xgboost_DEFAULT[[6]])[, 1:2]
xg_vp7 <- xgb.importance(model = google_xgboost_DEFAULT[[7]])[, 1:2]
xg_vp8 <- xgb.importance(model = google_xgboost_DEFAULT[[8]])[, 1:2]
xg_vp9 <- xgb.importance(model = google_xgboost_DEFAULT[[9]])[, 1:2]
xg_vp10 <- xgb.importance(model = google_xgboost_DEFAULT[[10]])[, 1:2]
xg_vp11 <- xgb.importance(model = google_xgboost_DEFAULT[[11]])[, 1:2]
xg_vp12 <- xgb.importance(model = google_xgboost_DEFAULT[[12]])[, 1:2]
xg_vp13 <- xgb.importance(model = google_xgboost_DEFAULT[[13]])[, 1:2]

xg_vp_1_13 <- rbind(xg_vp1, xg_vp2, xg_vp3, xg_vp5, xg_vp6, xg_vp7, xg_vp8, xg_vp9, xg_vp10, xg_vp11, xg_vp12, xg_vp13)#, xg_vp4

xg_vp_all <- xg_vp_1_13 %>% group_by(Feature) %>% summarise(mean_Gain = mean(Gain))
xg_vp_all <- arrange(xg_vp_all, mean_Gain %>% desc())

ggplot() +
  geom_bar(data = xg_vp_all[1:20, ], aes(x = reorder(Feature, mean_Gain), y = mean_Gain, fill = mean_Gain), stat = "identity", color = "darkgreen") + #, fill = "#FF79BC"
  theme_minimal() + 
  theme(axis.text.y = element_text(angle = 0, vjust = 0.3, size = 12, hjust = 1)) + 
  lims(y = c(0, 0.5)) + 
  labs(x = "var name", y = "avg imformation gain", title = "variable importance in xgboost (default param)") + 
  scale_fill_gradient2(low = "#A3D1D1", high = "#408080", mid = "#6FB7B7", midpoint = 0.25, limit = c(0, 0.5), space = "Lab", name = "Variable\nImportance") + 
  coord_flip()
```



